export const FETCH_USER_INPROGRESS = "FETCH_USER_INPROGRESS";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

export const FETCH_ALLTASK_INPROGRESS = "FETCH_ALLTASK_INPROGRESS";
export const FETCH_ALLTASK_SUCCESS = "FETCH_ALLTASK_SUCCESS";
export const FETCH_ALLTASK_ERROR = "FETCH_ALLTASK_ERROR";

export const ADD_NEW_TASK = "ADD_NEW_TASK";
export const ERROR = "ERROR";
export const EDIT_TASK = "EDIT_TASK";
export const UPDATE_EDITED_TASK = "UPDATE_EDITED_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
export const CLOSE_EDIT = "CLOSE_EDIT";
export const OPEN_TASK_DRAWER = "OPEN_TASK_DRAWER";
